### model
model_name_or_path: /share/home/sxjiang/model/Qwen2.5-7B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /share/home/zrchen/sxjiang-zr/ARPO-OCT/LLaMA-Factory/examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset_dir: dataset_info
dataset: final_5w4_still
template: qwen
cutoff_len: 4096
cutoff_len: 4096
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16
# resume_from_checkpoint: /share/home/sxjiang/myproject/ARPO-OCT/LLaMA-Factory/arpo_train_sft/checkpoints/checkpoint-600
# resume_from_checkpoint: /share/home/sxjiang/myproject/ARPO-OCT/LLaMA-Factory/arpo_train_sft/checkpoints/checkpoint-600
### output
output_dir: /share/home/zrchen/sxjiang-zr/ARPO-OCT/sft_checkpoints/Qwen2.5-7B-Instruct-arpo_final_sft_edition10-52
logging_steps: 10
save_steps: 100
save_steps: 100
plot_loss: true
overwrite_output_dir: false
overwrite_output_dir: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 7.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.1
weight_decay: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500


